### ISSUE TITLE
Error: Unknown SSL protocol error in connection to api.bls.gov:443

### ISSUE THREAD

**Issue by tiernanmartin** [mikeasilva/blsAPI#19] opened 2018-10-03 17:22 UTC
I am experiencing the following error when trying to use this package:

``` r

# API Version 1

response <- blsAPI::blsAPI("LAUCN040010000000005", api_version = 1)
## Error in function (type, msg, asError = TRUE) : Unknown SSL protocol error in connection to api.bls.gov:443

# API Version 2

response <- blsAPI::blsAPI("LAUCN040010000000005", api_version = 2)
## Error in function (type, msg, asError = TRUE) : Unknown SSL protocol error in connection to api.bls.gov:443
```

Thanks for your work on this package 👍 

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
## Session info -------------------------------------------------------------
##  setting  value                       
##  version  R version 3.5.1 (2018-07-02)
##  system   x86_64, mingw32             
##  ui       RTerm                       
##  language (EN)                        
##  collate  English_United States.1252  
##  tz       America/Los_Angeles         
##  date     2018-10-03
## Packages -----------------------------------------------------------------
##  package   * version   date       source                            
##  backports   1.1.2     2017-12-13 CRAN (R 3.5.0)                    
##  base      * 3.5.1     2018-07-02 local                             
##  bitops      1.0-6     2013-08-17 CRAN (R 3.5.0)                    
##  blsAPI      0.2.0     2018-10-03 Github (mikeasilva/blsAPI@11850a0)
##  compiler    3.5.1     2018-07-02 local                             
##  datasets  * 3.5.1     2018-07-02 local                             
##  devtools    1.13.6    2018-06-27 CRAN (R 3.5.1)                    
##  digest      0.6.15    2018-01-28 CRAN (R 3.5.1)                    
##  evaluate    0.11      2018-07-17 CRAN (R 3.5.1)                    
##  graphics  * 3.5.1     2018-07-02 local                             
##  grDevices * 3.5.1     2018-07-02 local                             
##  htmltools   0.3.6     2017-04-28 CRAN (R 3.5.1)                    
##  knitr       1.20      2018-02-20 CRAN (R 3.5.1)                    
##  magrittr    1.5       2014-11-22 CRAN (R 3.5.1)                    
##  memoise     1.1.0     2017-04-21 CRAN (R 3.5.1)                    
##  methods   * 3.5.1     2018-07-02 local                             
##  Rcpp        0.12.18   2018-07-23 CRAN (R 3.5.1)                    
##  RCurl       1.95-4.11 2018-07-15 CRAN (R 3.5.1)                    
##  rjson       0.2.20    2018-06-08 CRAN (R 3.5.0)                    
##  rmarkdown   1.10      2018-06-11 CRAN (R 3.5.1)                    
##  rprojroot   1.3-2     2018-01-03 CRAN (R 3.5.1)                    
##  stats     * 3.5.1     2018-07-02 local                             
##  stringi     1.2.3     2018-06-12 CRAN (R 3.5.1)                    
##  stringr     1.3.1     2018-05-10 CRAN (R 3.5.1)                    
##  tools       3.5.1     2018-07-02 local                             
##  utils     * 3.5.1     2018-07-02 local                             
##  withr       2.1.2     2018-03-15 CRAN (R 3.5.1)                    
##  yaml        2.1.19    2018-05-01 CRAN (R 3.5.1)
```

</details>

**Comment by tiernanmartin** [comment] 2018-10-04 16:16
I sent an email to the BLS API and they informed me that as of October 1, 2018 they no longer support Transport Layer Security (TLS) 1.0:

> Hello,
>
>Thank you for using BLS API. Please refer to the below link
 >
>https://www.bls.gov/bls/disable-transport-layer-security-1-0.htm
 >
>You may need to update / configure client libraries to connect using TLS 1.1 and higher (preferably TLS 1.2)
 >
>Thanks,
>Rajesh.

I checked my systems's TLS and it is indeed TSL 1.0:
``` r
RCurl::curlVersion()$ssl_version
## [1] "OpenSSL/1.0.0o"
```

I found that this problem has impacted [other packages](https://github.com/hiratake55/RForcecom/issues/42) and one [suggested solution](https://github.com/hiratake55/RForcecom/issues/42#issuecomment-229445012) is to convert `RCurl::curlPerfrom()` to `httr::VERB()`. I made an attempt to do this myself but unfortunately I am out of my depth.

**Comment by mikeasilva** [comment] 2018-10-05 23:01
@tiernanmartin .  Thanks for the bug report.  Will you please run libcurlVersion() and submit your output.  The package runs fine on my Linux machine.

**Comment by tiernanmartin** [comment] 2018-10-05 23:52
``` r
libcurlVersion()
## [1] "7.59.0"
## attr(,"ssl_version")
## [1] "OpenSSL/1.0.2n (WinSSL)"
## attr(,"libssh_version")
## [1] "libssh2/1.8.0"
## attr(,"protocols")
## [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"  
##  [9] "imaps"  "ldap"   "ldaps"  "pop3"   "pop3s"  "rtsp"   "scp"    "sftp"  
## [17] "smtp"   "smtps"  "telnet" "tftp"  
```

**Comment by doylek** [comment] 2018-10-17 20:36
@mikeasilva, I've forked the package and integrated httr instead of RCurl. Please feel free to test it out and implement the changes if you see fit. The new version is up and running with my scripts on my machine. 

I had the same problem on my Windows machine as @trijamms and @tiernanmartin with the same output from `libcurlVersion()`. This seems to be an issue with Windows + RCurl.

**Comment by tyoung94** [comment] 2018-10-18 13:12
doylek is a scholar and a gentleman. This fix works perfectly

**Comment by mikeasilva** [comment] 2018-10-23 17:16
@tiernanmartin, @trijamms, @pgg1309, @doylek, $tyoung94:

I think I have resolved this issue.  You will need to update the blsAPI package using devtools::install_github('mikeasilva/blsAPI').  Will you try it out and see if it works in your environments?

**Comment by doylek** [comment] 2018-10-23 20:07
No luck for me. I think the problem is with the `POST` call and how it treats `encode = "json"` differently than `httr::content_type_json()`. If I understood the documentation, the former attempts to perform formatting but the latter is just communicating content-type to the server.

**Comment by mikeasilva** [comment] 2018-10-24 02:00
@doylek - Sorry I missed your changes, but I folded them in.  Again please try it and confirm that it works for your situation.

**Comment by doylek** [comment] 2018-10-24 11:51
@mikeasilva I've installed the branch with the new code via `devtools::install_github('mikeasilva/blsAPI', ref = 'fix_issue_19')` and it's working well with my scripts. Thanks!

**Comment by mikeasilva** [comment] 2018-10-24 14:12
Fantastic news @doylek.  Thanks for your solution! @tyoung94 , @pgg1309 @tiernanmartin , @trijamms is it working for you?  I would love to close the issue and submit this to CRAN but want confirmation from someone else that it is working.

**Comment by tyoung94** [comment] 2018-10-24 15:19
I installed the package using doyleks code above and it works with my scripts! Thank you very much for this prompt update

**Comment by tiernanmartin** [comment] 2018-10-24 17:16
This fix works for me as well -- thank you!

**Comment by trijamms** [comment] 2018-10-24 17:30
Sorry to rain on the parade. I am getting a new error. Maybe it has something to do with using the option `return_data_frame = TRUE`. I ran the following line and got the error below. After installing doylek's fork, the error disappeared.

```
blsAPI(blsPayload, 2, T)
Error in fromJSON(json) : unexpected character '<'
```

**Comment by mikeasilva** [comment] 2018-10-25 17:17
Resolved with https://github.com/mikeasilva/blsAPI/commit/01d0669b260a2b82fda3486aa655612c16279cff

**Closed by mikeasilva** 2018-10-25 17:17 UTC
